kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-leader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vc01cl01-t0compute
  resources:
    requests:
      storage: 2Gi
